name: Anthony Lopes
description: My Personal Blog
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://anthonylopes.xyz'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'anthonylopes.xyz'
author:         'Anthony Lopes'
